### ISSUE TITLE
Compatibility Gnome 3.32

### ISSUE THREAD

**Issue by MasinAD** [sustmi/gnome-shell-extension-windowoverlay-icons#10]
Even while the extension doesn't throw any errors in Looking Glass, there are no icons in window overview.

**Comment by bryango** [comment]
This extension is so helpful when there's many windows, please fix! I've taken a look at the code and tried the mods suggested in <DreaminginCodeZH/gnome-shell-extension-es6-class-codemod>, but nothing happened.

**Comment by eode** [comment]
That PR works for me after the fix you pushed.

**Comment by barraponto** [comment]
I've been using the PR version successfully.

**Comment by sustmi** [comment]
The extension was updated to be compatible with GNOME Shell v3.32. The update will be released as v34 of the extension (if it passes the review process).

**Comment by barraponto** [comment]
No need to apologize, @sustmi 
We're grateful for all the effort maintaining this extension :cake:
