### ISSUE TITLE
Icon size doesn't count for scaling

### ISSUE THREAD

**Issue by snaggen** [sustmi/gnome-shell-extension-windowoverlay-icons#16]
I have a 4k screen on my laptop that uses 3840x2160 with 200% scaling, but when I connect it to a low DPI external monitor I run it in 1920x1080 with 100% scaling. On this setup everything should look the same size regardless of the resolution, however on my low dpi setup the overlay icons are twice the size from the hidpi setup. So it is clear that on the HIDPI case the scaling factor is not taken in to account when calculating the icon size.

**Comment by sustmi** [comment]
Hi @snaggen . Thanks for the pull request and sorry for the late response.
I am trying to reproduce the issue on my system using [fractional scaling](https://wiki.archlinux.org/index.php/HiDPI#Wayland) and it seems to work OK even without your changes.
Can you explain how you enable the scaling and what setup do you use (Wayland or X11)?

Here is a screenshot I took on my external monitor with 175% scaling and icon size set to 128 px. The frame in GIMP is also set to 128x128 px. You can see that the application icon has the same dimensions as the 128x128 px box even though it has 1.75x more pixels in reality.
![obrazek](https://user-images.githubusercontent.com/885946/88626629-73872880-d09a-11ea-89f7-f535352831d1.png)

I just want to understand how it works and make sure that your fix would not break behavior for someone else.

**Comment by sustmi** [comment]
I just checked that your change has no effect when scaling using the fractional scaling setting.
Still, I am curious how you do the scaling because I can see that when using the fractional scaling, the fonts are actually still low resolution and just blurred to more pixels.
![obrazek](https://user-images.githubusercontent.com/885946/88627716-489dd400-d09c-11ea-957a-e146e3920b7b.png)

**Comment by sustmi** [comment]
I think my screen has too low resolution for enabling 200% scaling in non-fractional mode.
I do not see this option in my screen settings neither with fractional scaling enabled nor when disabled.

But if it works:
- for you with 200% scaling
- for me with 175% fractional scaling 
- and without scaling

I am pretty confident that your changes should work for most of the people.
Thank you for your fix.
