### ISSUE TITLE
The transparency of the icons does not change, gnome 3.26

### ISSUE THREAD

**Issue by webmastak** [sustmi/gnome-shell-extension-windowoverlay-icons#3]
The transparency of the icons does not change, gnome 3.26
https://i.imgur.com/jMJ4u4z.png
https://i.imgur.com/PuUkFGl.png
https://i.imgur.com/OYRxJUK.png

**Comment by dsboger** [comment]
I proposed a fix in #2. It's really simple, so you could do it yourself while it is not resolved upstream.

**Comment by sustmi** [comment]
This issue was fixed thanks to @dsboger in https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/commit/ad7366d6dc78506a0c47b0b65fa9c3915e017625. The fix is released in v31 which will be available at https://extensions.gnome.org/extension/302/windowoverlay-icons/ after review.
