### ISSUE TITLE
Will you add icon shadow?

### ISSUE THREAD

**Issue by amivaleo** [sustmi/gnome-shell-extension-windowoverlay-icons#6]
Hi,

I'd like to know if you will ever add icon shadow. That could improve the visual experience.

Thank you!

**Comment by sustmi** [comment]
Hi, how exactly do you imagine the icon shadow?
How would it be different from setting the background to some semi-transparent color?
![Semi-transparent background](https://user-images.githubusercontent.com/885946/50054881-5e6cb880-0147-11e9-90bf-8561f9cd98e0.png)

**Comment by amivaleo** [comment]
Well, that's more a 'dark background' I think.
I mean more like a 'gradient': https://previews.123rf.com/images/asmati/asmati1706/asmati170606229/80944205-user-avatar-illustration-anonymous-sign-vector-white-icon-with-soft-shadow-on-transparent-background.jpg

**Comment by sustmi** [comment]
I wanted to use [drop-shadow CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow) but unfortunately GNOME Shell does not support it.

That means that we cannot have a shadow of an arbitrary shape.

Then I tried to use [box-shadow CSS property](https://www.cssmatic.com/box-shadow) but it looks like the [GNOME Shell implementation is strange](https://stackoverflow.com/a/17836401) and the best result I got was by using:
```css
background-color: rgba(255, 255, 255, 1.0);
box-shadow: 20px 20px 30px rgba(0, 0, 0, 1.0);
```
looks like this:
![box-shadow](https://user-images.githubusercontent.com/885946/50057190-21182300-0167-11e9-8209-811c43e5f32f.png)

**Comment by sustmi** [comment]
Unfortunately I do not know of any way how to get a shadow without the background itself.

**Comment by amivaleo** [comment]
I understand. :frowning_face: 
Well, that's the best you can come up with.

Thank you for your extension. :)
